# Generated by Django 5.0.2 on 2024-03-05 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('email', models.EmailField(max_length=50, unique=True)),
                ('tel', models.CharField(max_length=20, unique=True)),
                ('niu', models.CharField(max_length=15, unique=True)),
            ],
        ),
    ]
