# Generated by Django 4.0 on 2024-03-06 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('suppliers', '0001_initial'),
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='supplier',
            field=models.ManyToManyField(related_name='categories', to='suppliers.Supplier'),
        ),
    ]
